
    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companjujashd.companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table companies (
        id bigint generated by default as identity,
        cnpj varchar(255) unique,
        nome varchar(255),
        schema varchar(255) unique,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) check (name in ('ROLE_CUSTOMER','ROLE_ADMINISTRATOR')),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        cpf varchar(255),
        email varchar(255) unique,
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );
